# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1385, 733)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/nb.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 1000))
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 1381, 801))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMinimumSize(QtCore.QSize(1000, 500))
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_slide_menu = QtWidgets.QFrame(self.main_frame)
        self.left_slide_menu.setEnabled(True)
        self.left_slide_menu.setMinimumSize(QtCore.QSize(280, 0))
        self.left_slide_menu.setMaximumSize(QtCore.QSize(280, 16777215))
        self.left_slide_menu.setStyleSheet("")
        self.left_slide_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_slide_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_slide_menu.setLineWidth(1)
        self.left_slide_menu.setObjectName("left_slide_menu")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.left_slide_menu)
        self.verticalLayout_19.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.domain_conf = QtWidgets.QFrame(self.left_slide_menu)
        self.domain_conf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.domain_conf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.domain_conf.setObjectName("domain_conf")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.domain_conf)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.domain_label = QtWidgets.QLabel(self.domain_conf)
        self.domain_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.domain_label.setStyleSheet("background-color:black;\n"
"color:white;")
        self.domain_label.setAlignment(QtCore.Qt.AlignCenter)
        self.domain_label.setObjectName("domain_label")
        self.verticalLayout_20.addWidget(self.domain_label)
        self.domain_spin_box = QtWidgets.QSpinBox(self.domain_conf)
        self.domain_spin_box.setAlignment(QtCore.Qt.AlignCenter)
        self.domain_spin_box.setMaximum(232)
        self.domain_spin_box.setObjectName("domain_spin_box")
        self.verticalLayout_20.addWidget(self.domain_spin_box)
        self.apply_domain = QtWidgets.QPushButton(self.domain_conf)
        self.apply_domain.setStyleSheet("background-color:#FAF4C0;")
        self.apply_domain.setObjectName("apply_domain")
        self.verticalLayout_20.addWidget(self.apply_domain)
        self.verticalLayout_19.addWidget(self.domain_conf)
        self.tm_conf = QtWidgets.QFrame(self.left_slide_menu)
        self.tm_conf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tm_conf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tm_conf.setObjectName("tm_conf")
        self.layoutWidget = QtWidgets.QWidget(self.tm_conf)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 258, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.dds = QtWidgets.QPushButton(self.layoutWidget)
        self.dds.setObjectName("dds")
        self.verticalLayout_21.addWidget(self.dds)
        self.turnOn_terminator = QtWidgets.QPushButton(self.layoutWidget)
        self.turnOn_terminator.setObjectName("turnOn_terminator")
        self.verticalLayout_21.addWidget(self.turnOn_terminator)
        self.send_destination = QtWidgets.QPushButton(self.layoutWidget)
        self.send_destination.setObjectName("send_destination")
        self.verticalLayout_21.addWidget(self.send_destination)
        self.robot_sw_ver = QtWidgets.QPushButton(self.layoutWidget)
        self.robot_sw_ver.setObjectName("robot_sw_ver")
        self.verticalLayout_21.addWidget(self.robot_sw_ver)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rut_wifi = QtWidgets.QComboBox(self.layoutWidget)
        self.rut_wifi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rut_wifi.setMaxVisibleItems(0)
        self.rut_wifi.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.rut_wifi.setObjectName("rut_wifi")
        self.rut_wifi.addItem("")
        self.rut_wifi.addItem("")
        self.horizontalLayout_8.addWidget(self.rut_wifi)
        self.rut_wifi_button = QtWidgets.QPushButton(self.layoutWidget)
        self.rut_wifi_button.setObjectName("rut_wifi_button")
        self.horizontalLayout_8.addWidget(self.rut_wifi_button)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.verticalLayout_23.addLayout(self.verticalLayout_21)
        self.dds_output = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.dds_output.setMinimumSize(QtCore.QSize(0, 150))
        self.dds_output.setObjectName("dds_output")
        self.verticalLayout_23.addWidget(self.dds_output)
        self.verticalLayout_19.addWidget(self.tm_conf)
        self.alias_frame = QtWidgets.QFrame(self.left_slide_menu)
        self.alias_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.alias_frame.setStyleSheet("background-color:white;")
        self.alias_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alias_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alias_frame.setObjectName("alias_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.alias_frame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_7 = QtWidgets.QLabel(self.alias_frame)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setStyleSheet("background-color:black;\n"
"color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_22.addWidget(self.label_7)
        self.nb_ego_checkbox = QtWidgets.QCheckBox(self.alias_frame)
        self.nb_ego_checkbox.setMinimumSize(QtCore.QSize(0, 30))
        self.nb_ego_checkbox.setObjectName("nb_ego_checkbox")
        self.verticalLayout_22.addWidget(self.nb_ego_checkbox)
        self.debugData = QtWidgets.QCheckBox(self.alias_frame)
        self.debugData.setMinimumSize(QtCore.QSize(0, 30))
        self.debugData.setObjectName("debugData")
        self.verticalLayout_22.addWidget(self.debugData)
        self.verticalLayout_19.addWidget(self.alias_frame, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 7)
        self.verticalLayout_19.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.left_slide_menu)
        self.center_frame = QtWidgets.QFrame(self.main_frame)
        self.center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_frame.setObjectName("center_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.center_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_12 = QtWidgets.QFrame(self.center_frame)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sys_info = QtWidgets.QLabel(self.frame_12)
        self.sys_info.setStyleSheet("background-color:#FAF4C0;")
        self.sys_info.setText("")
        self.sys_info.setObjectName("sys_info")
        self.horizontalLayout_6.addWidget(self.sys_info)
        self.terminal = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        self.terminal.setStyleSheet("background-color: rgb(255, 192, 203);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../.designer/.designer/.designer/backup/icons/nb.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terminal.setIcon(icon1)
        self.terminal.setObjectName("terminal")
        self.horizontalLayout_6.addWidget(self.terminal)
        self.bagplay = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bagplay.sizePolicy().hasHeightForWidth())
        self.bagplay.setSizePolicy(sizePolicy)
        self.bagplay.setStyleSheet("background-color: rgb(173, 216, 230);\n"
"\n"
"")
        self.bagplay.setIcon(icon1)
        self.bagplay.setObjectName("bagplay")
        self.horizontalLayout_6.addWidget(self.bagplay)
        self.horizontalLayout_6.setStretch(0, 8)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.center_frame)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.robot_info = QtWidgets.QLabel(self.frame_13)
        self.robot_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.robot_info.setText("")
        self.robot_info.setObjectName("robot_info")
        self.horizontalLayout_7.addWidget(self.robot_info)
        self.service_info = QtWidgets.QLabel(self.frame_13)
        self.service_info.setText("")
        self.service_info.setObjectName("service_info")
        self.horizontalLayout_7.addWidget(self.service_info)
        self.cross_info = QtWidgets.QLabel(self.frame_13)
        self.cross_info.setText("")
        self.cross_info.setObjectName("cross_info")
        self.horizontalLayout_7.addWidget(self.cross_info)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 4)
        self.horizontalLayout_7.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame_13)
        self.top_view = QtWidgets.QFrame(self.center_frame)
        self.top_view.setMaximumSize(QtCore.QSize(16777215, 300))
        self.top_view.setStyleSheet("background-color:white;")
        self.top_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_view.setObjectName("top_view")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_view)
        self.horizontalLayout_2.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.behavior = QtWidgets.QFrame(self.top_view)
        self.behavior.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior.setObjectName("behavior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.behavior)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.behavior_label = QtWidgets.QFrame(self.behavior)
        self.behavior_label.setMaximumSize(QtCore.QSize(500, 30))
        self.behavior_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label.setObjectName("behavior_label")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.behavior_label)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.behavior_label)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setStyleSheet("background-color:yellow;")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.behavior_label)
        self.behavior_light = QtWidgets.QFrame(self.behavior)
        self.behavior_light.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_light.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_light.setObjectName("behavior_light")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.behavior_light)
        self.verticalLayout_10.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.destination = QtWidgets.QRadioButton(self.behavior_light)
        self.destination.setEnabled(False)
        self.destination.setStyleSheet("color:black;")
        self.destination.setCheckable(False)
        self.destination.setObjectName("destination")
        self.verticalLayout_10.addWidget(self.destination)
        self.direc_stop = QtWidgets.QRadioButton(self.behavior_light)
        self.direc_stop.setEnabled(False)
        self.direc_stop.setStyleSheet("color:black;")
        self.direc_stop.setObjectName("direc_stop")
        self.verticalLayout_10.addWidget(self.direc_stop)
        self.parking = QtWidgets.QRadioButton(self.behavior_light)
        self.parking.setEnabled(False)
        self.parking.setStyleSheet("color:black;")
        self.parking.setObjectName("parking")
        self.verticalLayout_10.addWidget(self.parking)
        self.parking_time = QtWidgets.QRadioButton(self.behavior_light)
        self.parking_time.setEnabled(False)
        self.parking_time.setStyleSheet("color:black;")
        self.parking_time.setObjectName("parking_time")
        self.verticalLayout_10.addWidget(self.parking_time)
        self.destination_changed = QtWidgets.QRadioButton(self.behavior_light)
        self.destination_changed.setEnabled(False)
        self.destination_changed.setStyleSheet("color:black;")
        self.destination_changed.setObjectName("destination_changed")
        self.verticalLayout_10.addWidget(self.destination_changed)
        self.person = QtWidgets.QRadioButton(self.behavior_light)
        self.person.setEnabled(False)
        self.person.setStyleSheet("color:black;")
        self.person.setCheckable(False)
        self.person.setObjectName("person")
        self.verticalLayout_10.addWidget(self.person)
        self.stop_automotic = QtWidgets.QRadioButton(self.behavior_light)
        self.stop_automotic.setEnabled(False)
        self.stop_automotic.setStyleSheet("color:black;")
        self.stop_automotic.setObjectName("stop_automotic")
        self.verticalLayout_10.addWidget(self.stop_automotic)
        self.hagang = QtWidgets.QRadioButton(self.behavior_light)
        self.hagang.setEnabled(False)
        self.hagang.setStyleSheet("color:black;")
        self.hagang.setObjectName("hagang")
        self.verticalLayout_10.addWidget(self.hagang)
        self.neubie = QtWidgets.QRadioButton(self.behavior_light)
        self.neubie.setEnabled(False)
        self.neubie.setStyleSheet("color:black;")
        self.neubie.setObjectName("neubie")
        self.verticalLayout_10.addWidget(self.neubie)
        self.no_road = QtWidgets.QRadioButton(self.behavior_light)
        self.no_road.setEnabled(False)
        self.no_road.setStyleSheet("color:black;")
        self.no_road.setObjectName("no_road")
        self.verticalLayout_10.addWidget(self.no_road)
        self.verticalLayout_2.addWidget(self.behavior_light)
        self.horizontalLayout_2.addWidget(self.behavior)
        self.sensor = QtWidgets.QFrame(self.top_view)
        self.sensor.setMaximumSize(QtCore.QSize(500, 16777215))
        self.sensor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor.setObjectName("sensor")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sensor)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.sensor)
        self.frame_3.setMaximumSize(QtCore.QSize(500, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setStyleSheet("background-color:yellow;")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.sensor_indi = QtWidgets.QFrame(self.sensor)
        self.sensor_indi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor_indi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor_indi.setObjectName("sensor_indi")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.sensor_indi)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.cam_f = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_f.setEnabled(False)
        self.cam_f.setStyleSheet("color:blackl;")
        self.cam_f.setObjectName("cam_f")
        self.verticalLayout_15.addWidget(self.cam_f)
        self.cam_fd = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_fd.setEnabled(False)
        self.cam_fd.setStyleSheet("color:blackl;")
        self.cam_fd.setObjectName("cam_fd")
        self.verticalLayout_15.addWidget(self.cam_fd)
        self.cam_fl = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_fl.setEnabled(False)
        self.cam_fl.setStyleSheet("color:blackl;")
        self.cam_fl.setObjectName("cam_fl")
        self.verticalLayout_15.addWidget(self.cam_fl)
        self.cam_fr = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_fr.setEnabled(False)
        self.cam_fr.setStyleSheet("color:blackl;")
        self.cam_fr.setObjectName("cam_fr")
        self.verticalLayout_15.addWidget(self.cam_fr)
        self.cam_bl = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_bl.setEnabled(False)
        self.cam_bl.setStyleSheet("color:blackl;")
        self.cam_bl.setObjectName("cam_bl")
        self.verticalLayout_15.addWidget(self.cam_bl)
        self.cam_br = QtWidgets.QRadioButton(self.sensor_indi)
        self.cam_br.setEnabled(False)
        self.cam_br.setStyleSheet("color:blackl;")
        self.cam_br.setObjectName("cam_br")
        self.verticalLayout_15.addWidget(self.cam_br)
        self.depth_fl = QtWidgets.QRadioButton(self.sensor_indi)
        self.depth_fl.setEnabled(False)
        self.depth_fl.setStyleSheet("color:blackl;")
        self.depth_fl.setObjectName("depth_fl")
        self.verticalLayout_15.addWidget(self.depth_fl)
        self.depth_fr = QtWidgets.QRadioButton(self.sensor_indi)
        self.depth_fr.setEnabled(False)
        self.depth_fr.setStyleSheet("color:blackl;")
        self.depth_fr.setObjectName("depth_fr")
        self.verticalLayout_15.addWidget(self.depth_fr)
        self.imu_port_status = QtWidgets.QRadioButton(self.sensor_indi)
        self.imu_port_status.setEnabled(False)
        self.imu_port_status.setStyleSheet("color:blackl;")
        self.imu_port_status.setObjectName("imu_port_status")
        self.verticalLayout_15.addWidget(self.imu_port_status)
        self.gnss_port_status = QtWidgets.QRadioButton(self.sensor_indi)
        self.gnss_port_status.setEnabled(False)
        self.gnss_port_status.setStyleSheet("color:blackl;")
        self.gnss_port_status.setObjectName("gnss_port_status")
        self.verticalLayout_15.addWidget(self.gnss_port_status)
        self.wheelodom_alive = QtWidgets.QRadioButton(self.sensor_indi)
        self.wheelodom_alive.setEnabled(False)
        self.wheelodom_alive.setStyleSheet("color:blackl;")
        self.wheelodom_alive.setObjectName("wheelodom_alive")
        self.verticalLayout_15.addWidget(self.wheelodom_alive)
        self.stm_port_status = QtWidgets.QRadioButton(self.sensor_indi)
        self.stm_port_status.setEnabled(False)
        self.stm_port_status.setStyleSheet("color:blackl;")
        self.stm_port_status.setObjectName("stm_port_status")
        self.verticalLayout_15.addWidget(self.stm_port_status)
        self.verticalLayout_4.addWidget(self.sensor_indi)
        self.horizontalLayout_2.addWidget(self.sensor)
        self.autonomy = QtWidgets.QFrame(self.top_view)
        self.autonomy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.autonomy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.autonomy.setObjectName("autonomy")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.autonomy)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.autonomy)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setStyleSheet("background-color:yellow;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.aut_dat_failure = QtWidgets.QFrame(self.autonomy)
        self.aut_dat_failure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aut_dat_failure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aut_dat_failure.setObjectName("aut_dat_failure")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.aut_dat_failure)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.ekf_alive = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.ekf_alive.setEnabled(False)
        self.ekf_alive.setStyleSheet("color:black;")
        self.ekf_alive.setObjectName("ekf_alive")
        self.verticalLayout_17.addWidget(self.ekf_alive)
        self.rtcm_alive = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.rtcm_alive.setEnabled(False)
        self.rtcm_alive.setStyleSheet("color:black;")
        self.rtcm_alive.setObjectName("rtcm_alive")
        self.verticalLayout_17.addWidget(self.rtcm_alive)
        self.ldm_msg = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.ldm_msg.setEnabled(False)
        self.ldm_msg.setStyleSheet("color:black;")
        self.ldm_msg.setObjectName("ldm_msg")
        self.verticalLayout_17.addWidget(self.ldm_msg)
        self.obstacles_tracking_msg = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.obstacles_tracking_msg.setEnabled(False)
        self.obstacles_tracking_msg.setStyleSheet("color:black;")
        self.obstacles_tracking_msg.setObjectName("obstacles_tracking_msg")
        self.verticalLayout_17.addWidget(self.obstacles_tracking_msg)
        self.gnss_alive = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.gnss_alive.setEnabled(False)
        self.gnss_alive.setStyleSheet("color:black;")
        self.gnss_alive.setObjectName("gnss_alive")
        self.verticalLayout_17.addWidget(self.gnss_alive)
        self.imu_alive = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.imu_alive.setEnabled(False)
        self.imu_alive.setStyleSheet("color:black;")
        self.imu_alive.setObjectName("imu_alive")
        self.verticalLayout_17.addWidget(self.imu_alive)
        self.odomgyro = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.odomgyro.setEnabled(False)
        self.odomgyro.setStyleSheet("color:black;")
        self.odomgyro.setObjectName("odomgyro")
        self.verticalLayout_17.addWidget(self.odomgyro)
        self.est_states_utm = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.est_states_utm.setEnabled(False)
        self.est_states_utm.setStyleSheet("color:black;")
        self.est_states_utm.setObjectName("est_states_utm")
        self.verticalLayout_17.addWidget(self.est_states_utm)
        self.no_way_tag = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.no_way_tag.setEnabled(False)
        self.no_way_tag.setStyleSheet("color:black;")
        self.no_way_tag.setObjectName("no_way_tag")
        self.verticalLayout_17.addWidget(self.no_way_tag)
        self.no_3d_height_rc = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.no_3d_height_rc.setEnabled(False)
        self.no_3d_height_rc.setStyleSheet("color:black;")
        self.no_3d_height_rc.setObjectName("no_3d_height_rc")
        self.verticalLayout_17.addWidget(self.no_3d_height_rc)
        self.no_3d_height_tr = QtWidgets.QRadioButton(self.aut_dat_failure)
        self.no_3d_height_tr.setEnabled(False)
        self.no_3d_height_tr.setStyleSheet("color:black;")
        self.no_3d_height_tr.setObjectName("no_3d_height_tr")
        self.verticalLayout_17.addWidget(self.no_3d_height_tr)
        self.verticalLayout_5.addWidget(self.aut_dat_failure)
        self.horizontalLayout_2.addWidget(self.autonomy)
        self.dangerous = QtWidgets.QFrame(self.top_view)
        self.dangerous.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dangerous.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dangerous.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dangerous.setObjectName("dangerous")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dangerous)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.dangerous)
        self.frame_6.setMaximumSize(QtCore.QSize(400, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setStyleSheet("background-color:yellow;")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.danger_indi = QtWidgets.QFrame(self.dangerous)
        self.danger_indi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.danger_indi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.danger_indi.setObjectName("danger_indi")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.danger_indi)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.unaccu_1m = QtWidgets.QRadioButton(self.danger_indi)
        self.unaccu_1m.setEnabled(False)
        self.unaccu_1m.setStyleSheet("color:black;")
        self.unaccu_1m.setObjectName("unaccu_1m")
        self.verticalLayout_16.addWidget(self.unaccu_1m)
        self.degree_120 = QtWidgets.QRadioButton(self.danger_indi)
        self.degree_120.setEnabled(False)
        self.degree_120.setStyleSheet("color:black;")
        self.degree_120.setObjectName("degree_120")
        self.verticalLayout_16.addWidget(self.degree_120)
        self.path_devia = QtWidgets.QRadioButton(self.danger_indi)
        self.path_devia.setEnabled(False)
        self.path_devia.setStyleSheet("color:black;")
        self.path_devia.setObjectName("path_devia")
        self.verticalLayout_16.addWidget(self.path_devia)
        self.pitch_roll = QtWidgets.QRadioButton(self.danger_indi)
        self.pitch_roll.setEnabled(False)
        self.pitch_roll.setStyleSheet("color:black;")
        self.pitch_roll.setObjectName("pitch_roll")
        self.verticalLayout_16.addWidget(self.pitch_roll)
        self.no_route_90 = QtWidgets.QRadioButton(self.danger_indi)
        self.no_route_90.setEnabled(False)
        self.no_route_90.setStyleSheet("color:black;")
        self.no_route_90.setObjectName("no_route_90")
        self.verticalLayout_16.addWidget(self.no_route_90)
        self.dr_gnss = QtWidgets.QRadioButton(self.danger_indi)
        self.dr_gnss.setEnabled(False)
        self.dr_gnss.setStyleSheet("color:black;")
        self.dr_gnss.setObjectName("dr_gnss")
        self.verticalLayout_16.addWidget(self.dr_gnss)
        self.open_cargo = QtWidgets.QRadioButton(self.danger_indi)
        self.open_cargo.setEnabled(False)
        self.open_cargo.setStyleSheet("color:black;")
        self.open_cargo.setObjectName("open_cargo")
        self.verticalLayout_16.addWidget(self.open_cargo)
        self.cliff_forked = QtWidgets.QRadioButton(self.danger_indi)
        self.cliff_forked.setEnabled(False)
        self.cliff_forked.setStyleSheet("color:black;")
        self.cliff_forked.setObjectName("cliff_forked")
        self.verticalLayout_16.addWidget(self.cliff_forked)
        self.verticalLayout_6.addWidget(self.danger_indi)
        self.horizontalLayout_2.addWidget(self.dangerous)
        self.crossing = QtWidgets.QFrame(self.top_view)
        self.crossing.setMaximumSize(QtCore.QSize(500, 16777215))
        self.crossing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.crossing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.crossing.setObjectName("crossing")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.crossing)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.crossing)
        self.frame_8.setMaximumSize(QtCore.QSize(400, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setStyleSheet("background-color:yellow;")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.cross_indi = QtWidgets.QFrame(self.crossing)
        self.cross_indi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cross_indi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cross_indi.setObjectName("cross_indi")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.cross_indi)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.not_crossing = QtWidgets.QRadioButton(self.cross_indi)
        self.not_crossing.setEnabled(False)
        self.not_crossing.setStyleSheet("color:black;")
        self.not_crossing.setObjectName("not_crossing")
        self.verticalLayout_18.addWidget(self.not_crossing)
        self.approch = QtWidgets.QRadioButton(self.cross_indi)
        self.approch.setEnabled(False)
        self.approch.setStyleSheet("color:black;")
        self.approch.setObjectName("approch")
        self.verticalLayout_18.addWidget(self.approch)
        self.wait = QtWidgets.QRadioButton(self.cross_indi)
        self.wait.setEnabled(False)
        self.wait.setStyleSheet("color:black;")
        self.wait.setObjectName("wait")
        self.verticalLayout_18.addWidget(self.wait)
        self.crossing_2 = QtWidgets.QRadioButton(self.cross_indi)
        self.crossing_2.setEnabled(False)
        self.crossing_2.setStyleSheet("color:black;")
        self.crossing_2.setObjectName("crossing_2")
        self.verticalLayout_18.addWidget(self.crossing_2)
        self.complete = QtWidgets.QRadioButton(self.cross_indi)
        self.complete.setObjectName("complete")
        self.verticalLayout_18.addWidget(self.complete)
        self.aborted = QtWidgets.QRadioButton(self.cross_indi)
        self.aborted.setObjectName("aborted")
        self.verticalLayout_18.addWidget(self.aborted)
        self.verticalLayout_7.addWidget(self.cross_indi)
        self.horizontalLayout_2.addWidget(self.crossing)
        self.verticalLayout.addWidget(self.top_view)
        self.bottom_log_view = QtWidgets.QFrame(self.center_frame)
        self.bottom_log_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_log_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_log_view.setObjectName("bottom_log_view")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.bottom_log_view)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_11 = QtWidgets.QFrame(self.bottom_log_view)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.behavior_2 = QtWidgets.QFrame(self.frame_11)
        self.behavior_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_2.setObjectName("behavior_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.behavior_2)
        self.verticalLayout_12.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.behavior_label_2 = QtWidgets.QFrame(self.behavior_2)
        self.behavior_label_2.setMaximumSize(QtCore.QSize(400, 30))
        self.behavior_label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label_2.setObjectName("behavior_label_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.behavior_label_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.behavior_label_2)
        self.label_6.setStyleSheet("background-color:yellow;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.verticalLayout_12.addWidget(self.behavior_label_2)
        self.behavior_light_2 = QtWidgets.QFrame(self.behavior_2)
        self.behavior_light_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light_2.setStyleSheet("background-color:white;")
        self.behavior_light_2.setObjectName("behavior_light_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.behavior_light_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.behavior_flags = QtWidgets.QLabel(self.behavior_light_2)
        self.behavior_flags.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_flags.setStyleSheet("border:none;")
        self.behavior_flags.setText("")
        self.behavior_flags.setWordWrap(True)
        self.behavior_flags.setObjectName("behavior_flags")
        self.verticalLayout_14.addWidget(self.behavior_flags)
        self.verticalLayout_12.addWidget(self.behavior_light_2)
        self.horizontalLayout_5.addWidget(self.behavior_2)
        self.behavior_5 = QtWidgets.QFrame(self.frame_11)
        self.behavior_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_5.setObjectName("behavior_5")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.behavior_5)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.behavior_label_9 = QtWidgets.QFrame(self.behavior_5)
        self.behavior_label_9.setMaximumSize(QtCore.QSize(400, 30))
        self.behavior_label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label_9.setObjectName("behavior_label_9")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.behavior_label_9)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_13 = QtWidgets.QLabel(self.behavior_label_9)
        self.label_13.setStyleSheet("background-color:yellow;")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_34.addWidget(self.label_13)
        self.verticalLayout_33.addWidget(self.behavior_label_9)
        self.behavior_light_9 = QtWidgets.QFrame(self.behavior_5)
        self.behavior_light_9.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light_9.setStyleSheet("background-color:white;")
        self.behavior_light_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_light_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_light_9.setObjectName("behavior_light_9")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.behavior_light_9)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.sensor_flags = QtWidgets.QLabel(self.behavior_light_9)
        self.sensor_flags.setMaximumSize(QtCore.QSize(500, 16777215))
        self.sensor_flags.setText("")
        self.sensor_flags.setWordWrap(True)
        self.sensor_flags.setObjectName("sensor_flags")
        self.verticalLayout_35.addWidget(self.sensor_flags)
        self.verticalLayout_33.addWidget(self.behavior_light_9)
        self.horizontalLayout_5.addWidget(self.behavior_5)
        self.behavior_3 = QtWidgets.QFrame(self.frame_11)
        self.behavior_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_3.setObjectName("behavior_3")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.behavior_3)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.behavior_label_7 = QtWidgets.QFrame(self.behavior_3)
        self.behavior_label_7.setMaximumSize(QtCore.QSize(400, 30))
        self.behavior_label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label_7.setObjectName("behavior_label_7")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.behavior_label_7)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_11 = QtWidgets.QLabel(self.behavior_label_7)
        self.label_11.setStyleSheet("background-color:yellow;")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_28.addWidget(self.label_11)
        self.verticalLayout_27.addWidget(self.behavior_label_7)
        self.behavior_light_7 = QtWidgets.QFrame(self.behavior_3)
        self.behavior_light_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light_7.setStyleSheet("background-color:white;")
        self.behavior_light_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_light_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_light_7.setObjectName("behavior_light_7")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.behavior_light_7)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.autonomy_data_failure = QtWidgets.QLabel(self.behavior_light_7)
        self.autonomy_data_failure.setMaximumSize(QtCore.QSize(500, 16777215))
        self.autonomy_data_failure.setText("")
        self.autonomy_data_failure.setWordWrap(True)
        self.autonomy_data_failure.setObjectName("autonomy_data_failure")
        self.verticalLayout_29.addWidget(self.autonomy_data_failure)
        self.verticalLayout_27.addWidget(self.behavior_light_7)
        self.horizontalLayout_5.addWidget(self.behavior_3)
        self.behavior_4 = QtWidgets.QFrame(self.frame_11)
        self.behavior_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_4.setObjectName("behavior_4")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.behavior_4)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.behavior_label_8 = QtWidgets.QFrame(self.behavior_4)
        self.behavior_label_8.setMaximumSize(QtCore.QSize(400, 30))
        self.behavior_label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label_8.setObjectName("behavior_label_8")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.behavior_label_8)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_12 = QtWidgets.QLabel(self.behavior_label_8)
        self.label_12.setStyleSheet("background-color:yellow;")
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_31.addWidget(self.label_12)
        self.verticalLayout_30.addWidget(self.behavior_label_8)
        self.behavior_light_8 = QtWidgets.QFrame(self.behavior_4)
        self.behavior_light_8.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light_8.setStyleSheet("background-color:white;")
        self.behavior_light_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_light_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_light_8.setObjectName("behavior_light_8")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.behavior_light_8)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.dangerous_flags = QtWidgets.QLabel(self.behavior_light_8)
        self.dangerous_flags.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dangerous_flags.setText("")
        self.dangerous_flags.setWordWrap(True)
        self.dangerous_flags.setObjectName("dangerous_flags")
        self.verticalLayout_32.addWidget(self.dangerous_flags)
        self.verticalLayout_30.addWidget(self.behavior_light_8)
        self.horizontalLayout_5.addWidget(self.behavior_4)
        self.behavior_6 = QtWidgets.QFrame(self.frame_11)
        self.behavior_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_6.setObjectName("behavior_6")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.behavior_6)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.behavior_label_10 = QtWidgets.QFrame(self.behavior_6)
        self.behavior_label_10.setMaximumSize(QtCore.QSize(400, 30))
        self.behavior_label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_label_10.setObjectName("behavior_label_10")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.behavior_label_10)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_14 = QtWidgets.QLabel(self.behavior_label_10)
        self.label_14.setStyleSheet("background-color:yellow;")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_37.addWidget(self.label_14)
        self.verticalLayout_36.addWidget(self.behavior_label_10)
        self.behavior_light_10 = QtWidgets.QFrame(self.behavior_6)
        self.behavior_light_10.setMaximumSize(QtCore.QSize(500, 16777215))
        self.behavior_light_10.setStyleSheet("background-color:white;")
        self.behavior_light_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.behavior_light_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.behavior_light_10.setObjectName("behavior_light_10")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.behavior_light_10)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.cross_flags = QtWidgets.QLabel(self.behavior_light_10)
        self.cross_flags.setMaximumSize(QtCore.QSize(500, 16777215))
        self.cross_flags.setText("")
        self.cross_flags.setWordWrap(True)
        self.cross_flags.setObjectName("cross_flags")
        self.verticalLayout_38.addWidget(self.cross_flags)
        self.verticalLayout_36.addWidget(self.behavior_light_10)
        self.horizontalLayout_5.addWidget(self.behavior_6)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.bottom_log_view)
        self.horizontalLayout.addWidget(self.center_frame)
        self.right_slide_menu = QtWidgets.QFrame(self.main_frame)
        self.right_slide_menu.setMaximumSize(QtCore.QSize(10, 16777215))
        self.right_slide_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_slide_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_slide_menu.setObjectName("right_slide_menu")
        self.horizontalLayout.addWidget(self.right_slide_menu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.domain_label.setText(_translate("MainWindow", "Domain 설정"))
        self.apply_domain.setText(_translate("MainWindow", "적용"))
        self.dds.setText(_translate("MainWindow", "set_cyclone_DDS"))
        self.turnOn_terminator.setText(_translate("MainWindow", "Terminator On"))
        self.send_destination.setText(_translate("MainWindow", "Pub service_target once"))
        self.robot_sw_ver.setText(_translate("MainWindow", "SSH 로봇 버전확인"))
        self.rut_wifi.setItemText(0, _translate("MainWindow", "12호기"))
        self.rut_wifi.setItemText(1, _translate("MainWindow", "24호기"))
        self.rut_wifi_button.setText(_translate("MainWindow", "verify_rut_wifi"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Topic 추가</p></body></html>"))
        self.nb_ego_checkbox.setText(_translate("MainWindow", "/nb_ego_status_logger"))
        self.debugData.setText(_translate("MainWindow", "debugData"))
        self.terminal.setText(_translate("MainWindow", "Tm and Topic"))
        self.bagplay.setText(_translate("MainWindow", "Bagplay(TBD)"))
        self.label.setText(_translate("MainWindow", "Behavior_indication"))
        self.destination.setText(_translate("MainWindow", "1.종착지 5m 근접"))
        self.direc_stop.setText(_translate("MainWindow", "2.신호대기 정지"))
        self.parking.setText(_translate("MainWindow", "4.갓길 이동 및 정지1"))
        self.parking_time.setText(_translate("MainWindow", "8.갓길 이동 및 정지2"))
        self.destination_changed.setText(_translate("MainWindow", "16.출발 전 헤딩정렬"))
        self.person.setText(_translate("MainWindow", "32.보행자대상 감속"))
        self.stop_automotic.setText(_translate("MainWindow", "64.자율주행중단상태"))
        self.hagang.setText(_translate("MainWindow", "128.하강경사로감속행동"))
        self.neubie.setText(_translate("MainWindow", "256.뉴비대상감속"))
        self.no_road.setText(_translate("MainWindow", "512.전방주행영역인지"))
        self.label_2.setText(_translate("MainWindow", "sensor_indication (Topic loss)"))
        self.cam_f.setText(_translate("MainWindow", "/cam_f/symbolic_link_alive 3s"))
        self.cam_fd.setText(_translate("MainWindow", "/cam_fd/symbolic_link_alive 3s"))
        self.cam_fl.setText(_translate("MainWindow", "/cam_fl/symbolic_link_alive 3s"))
        self.cam_fr.setText(_translate("MainWindow", "/cam_fr/symbolic_link_alive 3s"))
        self.cam_bl.setText(_translate("MainWindow", "/cam_bl/symbolic_link_alive 3s"))
        self.cam_br.setText(_translate("MainWindow", "/cam_br/symbolic_link_alive 3s"))
        self.depth_fl.setText(_translate("MainWindow", "/depth_fl/symbolic_link_alive 3s"))
        self.depth_fr.setText(_translate("MainWindow", "/depth_fr/symbolic_link_alive 3s"))
        self.imu_port_status.setText(_translate("MainWindow", "/imu_port_status 3s"))
        self.gnss_port_status.setText(_translate("MainWindow", "/gnss_port_status 3s"))
        self.wheelodom_alive.setText(_translate("MainWindow", "/wheelodom_alive 3s"))
        self.stm_port_status.setText(_translate("MainWindow", "/stm_port_status 3s"))
        self.label_3.setText(_translate("MainWindow", "aut_dat_indication"))
        self.ekf_alive.setText(_translate("MainWindow", "/ekf_alive 3s"))
        self.rtcm_alive.setText(_translate("MainWindow", "/rtcm_alive 3s"))
        self.ldm_msg.setText(_translate("MainWindow", "/ldm_msg 1s"))
        self.obstacles_tracking_msg.setText(_translate("MainWindow", "/obstacles_tracking_msg 0.5"))
        self.gnss_alive.setText(_translate("MainWindow", "/gnss_alive 3s"))
        self.imu_alive.setText(_translate("MainWindow", "/imu_alive 3s"))
        self.odomgyro.setText(_translate("MainWindow", "/odomgyro 0.1s"))
        self.est_states_utm.setText(_translate("MainWindow", "/est_states_utm 0.1s"))
        self.no_way_tag.setText(_translate("MainWindow", "전역경로 way tag 정보 없음"))
        self.no_3d_height_rc.setText(_translate("MainWindow", "ldm_msg에 3d height 없음"))
        self.no_3d_height_tr.setText(_translate("MainWindow", "ldm_msg에 3 height 없음(송신)"))
        self.label_4.setText(_translate("MainWindow", "dangerous_indication"))
        self.unaccu_1m.setText(_translate("MainWindow", "누적거리 1m 이하(20초)"))
        self.degree_120.setText(_translate("MainWindow", "120도 차이"))
        self.path_devia.setText(_translate("MainWindow", "경로이탈 (4m/이면도로7m)"))
        self.pitch_roll.setText(_translate("MainWindow", "pitch.roll 33도 이상"))
        self.no_route_90.setText(_translate("MainWindow", "주행불가영역 90% 이상"))
        self.dr_gnss.setText(_translate("MainWindow", "DR과 gnss위치 오차데이터 위험"))
        self.open_cargo.setText(_translate("MainWindow", "적재함 열린 상태 주행"))
        self.cliff_forked.setText(_translate("MainWindow", "낭떠러지구간(cliff) & forked_road"))
        self.label_5.setText(_translate("MainWindow", "corss_indication"))
        self.not_crossing.setText(_translate("MainWindow", "Not crossing"))
        self.approch.setText(_translate("MainWindow", "Approching"))
        self.wait.setText(_translate("MainWindow", "Waiting"))
        self.crossing_2.setText(_translate("MainWindow", "crossing"))
        self.complete.setText(_translate("MainWindow", "Completed"))
        self.aborted.setText(_translate("MainWindow", "Aborted"))
        self.label_6.setText(_translate("MainWindow", "Behavior_description"))
        self.label_13.setText(_translate("MainWindow", "sensor_description"))
        self.label_11.setText(_translate("MainWindow", "aut_dat_description"))
        self.label_12.setText(_translate("MainWindow", "dangerous_description"))
        self.label_14.setText(_translate("MainWindow", "cross_description"))
